configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hyperaide%2Fuserplex-e3b56018e46f27b9b6df088adfd4811dae8518be16dfabc0039b13e6addc5dc9.yml
openapi_spec_hash: dab8b821b913a3ecfaf492cda2a1c093
config_hash: e260d0cb2c723ee5ea55436af680d9bd
